### PR TITLE
Implemented waitfor

### PR DESCRIPTION
**Pull request by cernec1999**

### CODE REVIEW

**Review by xtjoeytx — COMMENTED** [review]
Does waitfor return anything?

**Comment by cernec1999** [comment]
Yes, it returns a Boolean. True, if the event was caught, and false if it timed out.

**Comment by cernec1999** [comment]
Attaching CFG for `waitfor` from official compiler:

```js
//#CLIENTSIDE
function onCreated() {
    waitForMessage();
}

function onPlayerChats() {
    if (player.chat == "foo") {
        this.trigger("foo");
    }
}

function waitForMessage() {
    temp.hello = waitfor(this, "foo", 7200);
    player.chat = "bar";
}
```

graphviz-7

**Review by xtjoeytx — APPROVED** [review]
Lgtm

**Pull request merged**
